name: av_sample
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: "^3.5.4"

dependencies:
  flutter:
    sdk: flutter

  # Add other dependencies here
  cupertino_icons: ^1.0.2

  # Using for dependency injection
  get_it: ^8.0.2
  equatable: ^2.0.7

  # Using to receive results from repository
  dartz: ^0.10.0
  intl: ^0.19.0

  # Using to state management
  flutter_bloc: ^8.1.6
  mockito: ^5.4.4
  bloc_test: ^9.1.7



dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  patrol: ^3.13.0

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/responses/
